dist: bionic
language: node_js
node_js:
  - 8

before_script:
  - npm install
  - npm install -g mocha
  - npm install --save-dev @commitlint/travis-cli
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

script:
  - commitlint-travis
  - npm test
