name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: install LCUI
      run: |
        wget https://github.com/lc-soft/LCUI/archive/develop.zip -O LCUI-develop.zip
        unzip LCUI-develop.zip
        rm LCUI-develop.zip
        cd LCUI-develop
        sh ./autogen.sh
        ./configure
        make
        sudo make install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - name: Run test
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        npm install -g mocha
        npm test
      env:
        CI: true
